# Generated by Django 4.2 on 2023-04-28 08:17

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_alter_post_liked_by_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="count_comments",
        ),
        migrations.RemoveField(
            model_name="post",
            name="count_likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="liked_by",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.profile_picture_file_path
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
