# Generated by Django 4.2 on 2023-04-28 08:17

from django.conf import settings
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True, upload_to=user.models.profile_picture_file_path
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                related_name="user_follows", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
